### ISSUE TITLE
Error in sending job information

### ISSUE THREAD

**Issue by prithi** [aetros/aetros-cli#10]
I am getting this error when running my code.

`Training status changed to TRAINING
Error in sending job information: {"error":"InvalidArgumentException","message":"id is required"}`

![capture](https://cloud.githubusercontent.com/assets/2114722/19609091/f163ec24-97f6-11e6-9dc6-3e92b553a294.PNG)

**Comment by marcj** [comment]
https://github.com/aetros/aetros-cli#api-key

**Comment by prithi** [comment]
API_KEY was set as a user variable.

**Comment by prithi** [comment]
When I run the code, I can see my network is training. However, after 2 or 3 seconds training stopped.

**Comment by marcj** [comment]
Whats your code?

**Comment by prithi** [comment]
Sorry, when I run the code, I can see in the aetros trainer page that my network has started to train. Even I can see my gpu, cpu loads are updating in the aetros. However, after 5-10 seconds later, everything stopped updating in the aetros page.

**Comment by marcj** [comment]
This has been fixed and will be released shortly. Thanks for reporting!

**Comment by marcj** [comment]
Should be fixed in v0.4.0.
