### ISSUE TITLE
Failed to find libhdf5.h during instalation

### ISSUE THREAD

**Issue by ikhlestov** [aetros/aetros-cli#15]
Hi!
I've tried to build your client on my local computer inside clear virtualenv. On the ubuntu 16.04 it failed with following error:
```
In file included from /tmp/easy_install-bwpD2f/h5py-2.7.0rc2/h5py/defs.c:470:0:
/tmp/easy_install-bwpD2f/h5py-2.7.0rc2/h5py/api_compat.h:27:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
After few tries I've fixed this error by manually installing `h5py` package with pip. And it seems something strange - `h5py` exist inside setup.py install_requires list, but was not installed correct way.
Maybe this info will be helpful for you for future development.

**Comment by marcj** [comment]
Oh weird. So you have install via `pip install hdf5` and then  `pip install aetros` did work?

**Comment by ikhlestov** [comment]
No, it related to Installation development version.
Steps to reproduce(i've just checked again)
```
$ git clone https://github.com/aetros/aetros-cli.git
$ cd aetros-cli
$ virtualenv -p python .env
$ source .evn/bin/activate
$ python setup.py install
...
# exception raised
```
If previous to `python setup.py install` install h2py manually all works fine:
```
$ pip install h5py
$ python setup.py install
...
# installation completed successfully
```
I have no idea why this happen.
Also I've noted that during h5py installation numpy also was installed. So prior setup.py h5py and numpy already exist. Maybe it can be related somehow.

**Comment by marcj** [comment]
That is really weird. `python setup.py install` should actually install anything we have declared as dependency. We have no special building routine, just a few regular python libraries as dependency. If they don't get installed automatically I guess it's an issue with pip.

**Comment by marcj** [comment]
Okay, we added `make dev-install` which should now install correctly all dependencies.
