### ISSUE TITLE
Invalid param name --secure-key when runnning model locally

### ISSUE THREAD

**Issue by ikhlestov** [aetros/aetros-cli#16]
When new job were defined through GUI such message appear:
```
aetros start 1WPX06QP0 --secure-key=YOUR_KEY
```
but if we try to run this command we receive such exception:
```
aetros start: error: unrecognized arguments: --secure-key=my_key_id
```
Reading --help message for start I understood that it should be called with `--api-key=` param like:
```
aetros start 1WPX06QP0 --api-key=my_key_id
```
I think param name inside GUI or inside backend should be changed.

**Comment by marcj** [comment]
Thanks for reporting! Is fixed
