### ISSUE TITLE
KeyError: 'id'

### ISSUE THREAD

**Issue by anselal** [aetros/aetros-cli#19]
Hi,

I am running aetros 0.9.9 on a Windows 7 machine. I managed to successfully run the mnist-digits classifier with no errors. (Thanks by the way for fixing https://github.com/aetros/aetros-cli/issues/17 ).
I created my own digits dataset which I uploaded to aetros. I duplicated the mnist model and updated it to load my new dataset. I also updated the input dimensions. When I run the job I get the following error:

`  File "F:\Development\Python35-keras2-tf-gpu\lib\site-packages\aetros\auto_dataset.py", line 544, in get_images
    if image['id'] in images and os.path.isfile(images[image['id']]):
KeyError: 'id' `

**Comment by marcj** [comment]
Can you give me the name of your dataset and model? Then I can take a look into it.

**Comment by anselal** [comment]
The dataset is `soulis/dataset/alpr_digits` and the model is `soulis/alpr_digits_cnn`

**Comment by marcj** [comment]
Alrighty, that should be fixed in the newest version.
