### ISSUE TITLE
bash: aetros: command not found in Win10

### ISSUE THREAD

**Issue by PAK90** [aetros/aetros-cli#20]
I'm using Windows 10 and Python 3.5.2, I did `python -m pip install aetros` but I can't find the `aetros` command in normal cmd or Git Bash. I can however import aetros as a python module, but that doesn't help me to run a simple model locally on my machine.

**Comment by marcj** [comment]
If you haven't the bin dir of your python libraries in your PATH, you can also call aetros commands via `python -m aetros`, example `python -m aetros start marcj/model-name`

**Comment by PAK90** [comment]
Perfect, that fixed the issue, thanks.

A minor additional question; I ran the simple cats/dogs test model locally and the 'stats' page of the model didn't report any GPU usage (it says 'n/a'), despite the fact that this training did in fact use my gpu. At the top it lists as 'device' my CPU, while in the logs it says `Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:01:00.0)`.

**Comment by marcj** [comment]
which aetros version do you use? In the newest we should display the gpu memory usage also for Tensorflow. But we haven't found a way yet to detect, if Tensorflow uses a gpu and which.
