### ISSUE TITLE
Running local code

### ISSUE THREAD

**Issue by myhussien** [aetros/aetros-cli#27]
@marcj First, thanks for the great effort in making this GUI. Please excuse the questions if they sound very simple.

1) - I think my issue is the lack of documented examples (examples in general) in the repository. I'm trying to run the simple Keras mnist_cnn code. I have a very powerful local machine, and ssh is already set up.  After I define the model I added this:

```
job = aetros.backend.start_job('<username>/mnist_cnn')
for i in range(0, 100):
     model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
     job.progress(epoch=i, total=100)
job.done()
```

When the model starts training, it shows in trainer that it is alive, but everything is blank. What should I do to output the progress plots, insights, channels, etc. ?

2) -  For mnist_cnn example, mnist_data already comes with the package. If I have my own local data files, is there anything special I have to do to access them during training? Currently, before I run the code, I push it to my account at Aetros. Then I run the code locally. `python my_code.py`. This makes my unsure of how accessing the data is handled. Is it locally, or do we have to upload it somewhere on Aetros. Please clarify.

3) - If I stop the job, then restart it. I get a code to use. When I run the code I get the following error `Exception: Server python script is not configured. Aborted`. What does this mean? and how should I go about fixing it?

4) - It is says in the documentation that hyper-parameters optimization is easy with Aetros. Is it possible to have an complete example in the repository to show how one can do that? 

Thanks again,
-M

**Comment by marcj** [comment]
Hey, we released a couple of days after this issue a new minor version that improved a lot of usability issues. Please read the new Getting Started guide at https://aetros.com/docu/trainer/getting-started. The should clarify a lot of things.
Regarding your questions.

1. > What should I do to output the progress plots, insights, channels, etc. ?
You should use the methods available in the `job` object that come from the Python SDK. See https://aetros.com/docu/python-sdk/getting-started.
2. That has been changed in the new major version. Please read the Getting Started guide to get more information. You don't need to upload the code first. You can use just `aetros run` in a local directory where your source code is. In the Getting Started guide you see examples.
3. This wasn't possible before easily. We made it now very easy by attaching always all necessary source code files to the job's Git tree, which makes it possible to restart jobs without doing something special beforehand.
4. We're working on a video series that covers that as well. Is there something not clear in the Hyperparamter optimization guide? https://aetros.com/docu/trainer/features/hyperparameter-optimization

**Comment by marcj** [comment]
Since we overhauled the application and workflow, and questions have been answered, I'm going to close this. Feel free to add additional notes so I can reopen if necessary.
