### ISSUE TITLE
Starter stuck when job is failed/done too quickly

### ISSUE THREAD

**Issue by mbelousov** [aetros/aetros-cli#29]
Consider the example when job has failed too quickly (for instance, due to the invalid parameter value), in such case job status will be changed to `FAILED` and stuck forever (with running processes). It will similarly stuck when job is successfully finished. 

To replicate use the following script and run it with starter `aetros run --local`:
```python
import aetros.backend

if __name__ == '__main__':
    job = aetros.backend.context()
    raise IOError("File not found")
```
However, if you run it with `python quick.py` it will finish properly (i.e. status will be changed to `STOPPED`), which suggests that the problem is with aetros starter.
Interestingly, that when you run it in debug mode `DEBUG=1 aetros run --local` or add delay `sleep(1)` after job initialisation, it will also finish properly. Might be something related to race conditions / async issues (i.e. when job hasn't initialised properly but already finished)

**Comment by marcj** [comment]
Smells like a race condition in starter.py. Thanks for the report, I'm going to look at it and report back.

**Comment by marcj** [comment]
We fixed the bug and will release the fix shortly. Thanks for the detailed report again. :)

If you find it doesn't work when we release our next release 2018.1 next week, please report back.
