### ISSUE TITLE
Connection times out

### ISSUE THREAD

**Issue by haehn** [aetros/aetros-cli#7]
During training, the connection times out and aetros.com is not reachable from the network anymore. After 10 minutes or so, aetros.com is again reachable. I tested this on multiple different networks.

```
Epoch 13: loss=0.039863, acc=0.988683, val_loss=0.054563, val_acc=0.987000
Epoch 14: loss=0.039226, acc=0.988967, val_loss=0.055365, val_acc=0.986900
Epoch 15: loss=0.038914, acc=0.989067, val_loss=0.057667, val_acc=0.986500
Sync weights ...
Crashed ...
ERROR:root:Traceback (most recent call last):
  File "/home/d/AETROS/local/lib/python2.7/site-packages/aetros/starter.py", line 94, in start
    job_model.sync_weights()
  File "/home/d/AETROS/local/lib/python2.7/site-packages/aetros/JobModel.py", line 223, in sync_weights
    self.backend.upload_weights('best.hdf5', self.get_weights_filepath_best(), with_status=True)
  File "/home/d/AETROS/local/lib/python2.7/site-packages/aetros/AetrosBackend.py", line 227, in upload_weights
    response = requests.post(url, data=body, headers=headers)
  File "/home/d/AETROS/local/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/d/AETROS/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/d/AETROS/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/d/AETROS/local/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/d/AETROS/local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='aetros.com', port=80): Max retries exceeded with url: /api/job/weights?id=JmvGARpLb&accuracy=-1.000000.2&token=94dc9107aa68bc7c9307257df82928c6 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbfbf2a5990>: Failed to establish a new connection: [Errno 110] Connection timed out',))


```

**Comment by haehn** [comment]
here a traceroute from a "blocked" machine (which worked 10 minutes ago and then stopped during training):
http://pastebin.com/CaNBTp97

and here at the same time a traceroute from a non-blocked machine (which will be blocked if I start training after ~10 epochs):

http://pastebin.com/UkWBrVXF

**Comment by marcj** [comment]
Looks to me like telia.net is blocking the request? We have on our machine no auto-blocking, also in our current firewall nobody got blocked in the last days. Since telia.net is the latest point it can reach, and between it and aetros.com is at least one of our service provider (ispgateway.de) you should definitely be able to reach, I guess telia.net is blocking stuff for you. Have you tested it with a different ISP?

Can you give me your training id/network name?

**Comment by haehn** [comment]
I tried with two different ISPS. I guess all the traffic to your server from overseas gets rooted through telia?

**Comment by haehn** [comment]
bumping this.. really want to use aetros here at harvard

**Comment by marcj** [comment]
Should be fixed in v0.4.0. Please try it again with that version

**Comment by marcj** [comment]
We completely reworked the communication and switched to raw sockets instead of http. Please use newest version.

**Comment by haehn** [comment]
awesome, thanks!
