### ISSUE TITLE
about windows system

### ISSUE THREAD

**Issue by king33yoyo** [aetros/aetros-cli#8]
$ API_KEY='MY_API_KEY' aetros start my/my-network --insights
This order can not run in windows system,says "API_KEY"is not a internal command.
whether or not the windows syetem can not support aetros?
Thank you very much!

**Comment by marcj** [comment]
You can add API_KEY as user environment variable so you don't need to place it before the command.

**Comment by king33yoyo** [comment]
Thank you for your answer, I add API_KEY as my environment variable,but it still doesn't work.
Exception: Could not create training: {"error":"access_denied","message":"Access denied. API_KEY\/token correct?"}
I have checked my API_KEY,it is not wrong.What should I do?

**Comment by king33yoyo** [comment]
Thank you for your answer, I add API_KEY as my environment variable,but it still doesn't work.
Exception: Could not create training: {"error":"access_denied","message":"Access denied. API_KEY\/token correct?"}
I have checked my API_KEY,it is not wrong.What should I do?

**Comment by king33yoyo** [comment]
I reboot my computer,and it works!
But appear an another problem when I run dog-cat-classifier,it shop at prepare image for long time.
Are there any method to downlord these images first?

**Comment by king33yoyo** [comment]
It's me again,I run the /digit-convolution program,and show "UnicodeDecodeError: 'ascii' codec can't decode byte 0xd5 in position 11: ordinal not in range(128)", I check it on internet ,people say it is a language problem ,whether or not because I use the Chinese system,and how should I do to slove the problem?

**Comment by king33yoyo** [comment]
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
add above programe,the problem sloved.

**Comment by marcj** [comment]
Should be fixed in v0.4.0.
