### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by weiyu322** [aetros/aetros-cli#9]
ValueError: No JSON object could be decoded while run API_KEY='fc605a322ceea8bab59b2acde592d793' aetros start weiyu322/digit-convolution --insights

**Comment by weiyu322** [comment]
![image](https://cloud.githubusercontent.com/assets/15629565/18702887/3badd09a-8016-11e6-9b1f-dbf2c12894ac.png)

**Comment by marcj** [comment]
This should be fixed with https://github.com/aetros/aetros-cli/pull/14 and is going to be released soon

**Comment by marcj** [comment]
Should be fixed in v0.4.0.
